version: '3.3'

services:
  frontend:
    image: 'ghcr.io/embedbuilder/website:main'
    restart: unless-stopped
    networks:
      - embedbuilder
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgresql://embedbuilder:embedbuilder@postgres:5432/embedbuilder?schema=public
  postgres:
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_USER: embedbuilder
      POSTGRES_PASSWORD: embedbuilder
      POSTGRES_DB: embedbuilder
    networks:
      - embedbuilder
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD', 'pg_isready', '-q', '-d', 'embedbuilder', '-U', 'embedbuilder']
      interval: 3s
      timeout: 3s
      retries: 15

networks:
  embedbuilder:
    driver: bridge

volumes:
  postgres:
    driver: local
